/* DO NOT EDIT THIS FILE. This file is generated by scripts/generate-intrinsics.js */

export type VoidElem = "area" | "base" | "br" | "col" | "embed" | "hr" | "img" | "input" | "link" | "meta" | "param" | "source" | "track" | "wbr";

export function isVoidElem(name: string): name is VoidElem {
  switch (name) {
    case "area":
    case "base":
    case "br":
    case "col":
    case "embed":
    case "hr":
    case "img":
    case "input":
    case "link":
    case "meta":
    case "param":
    case "source":
    case "track":
    case "wbr":
      return true;
  }

  return false;
}
