/* DO NOT EDIT THIS FILE. This file is generated by scripts/generate-intrinsics.js */

declare namespace JSX {
  interface IntrinsicElements {
    a: HtmlGlobalAttributes & {
      download?: any;
      href?: any;
      hreflang?: any;
      media?: any;
      ping?: any;
      referrerpolicy?: any;
      rel?: any;
      shape?: any;
      target?: any;
    };
    abbr: HtmlGlobalAttributes;
    acronym: HtmlGlobalAttributes;
    address: HtmlGlobalAttributes;
    area: HtmlGlobalAttributes & {
      alt?: any;
      coords?: any;
      download?: any;
      href?: any;
      media?: any;
      ping?: any;
      referrerpolicy?: any;
      rel?: any;
      shape?: any;
      target?: any;
    };
    article: HtmlGlobalAttributes;
    aside: HtmlGlobalAttributes;
    audio: HtmlGlobalAttributes & {
      autoplay?: any;
      controls?: any;
      crossorigin?: any;
      loop?: any;
      muted?: any;
      preload?: any;
      src?: any;
    };
    b: HtmlGlobalAttributes;
    base: HtmlGlobalAttributes & {
      href?: any;
      target?: any;
    };
    bdi: HtmlGlobalAttributes;
    bdo: HtmlGlobalAttributes;
    big: HtmlGlobalAttributes;
    blockquote: HtmlGlobalAttributes & {
      cite?: any;
    };
    body: HtmlGlobalAttributes;
    br: HtmlGlobalAttributes;
    button: HtmlGlobalAttributes & {
      disabled?: any;
      form?: any;
      formaction?: any;
      formenctype?: any;
      formmethod?: any;
      formnovalidate?: any;
      formtarget?: any;
      name?: any;
      type?: any;
      value?: any;
    };
    canvas: HtmlGlobalAttributes & {
      width?: any;
    };
    caption: HtmlGlobalAttributes & {
      align?: any;
    };
    center: HtmlGlobalAttributes;
    cite: HtmlGlobalAttributes;
    code: HtmlGlobalAttributes;
    col: HtmlGlobalAttributes & {
      align?: any;
      span?: any;
    };
    colgroup: HtmlGlobalAttributes & {
      align?: any;
      span?: any;
    };
    content: HtmlGlobalAttributes;
    data: HtmlGlobalAttributes & {
      value?: any;
    };
    datalist: HtmlGlobalAttributes;
    dd: HtmlGlobalAttributes;
    del: HtmlGlobalAttributes & {
      cite?: any;
      datetime?: any;
    };
    details: HtmlGlobalAttributes & {
      open?: any;
    };
    dfn: HtmlGlobalAttributes;
    dialog: HtmlGlobalAttributes & {
      open?: any;
    };
    dir: HtmlGlobalAttributes;
    div: HtmlGlobalAttributes & {
      width?: any;
    };
    dl: HtmlGlobalAttributes;
    dt: HtmlGlobalAttributes;
    em: HtmlGlobalAttributes;
    embed: HtmlGlobalAttributes & {
      src?: any;
      type?: any;
      width?: any;
    };
    fieldset: HtmlGlobalAttributes & {
      disabled?: any;
      form?: any;
      name?: any;
    };
    figcaption: HtmlGlobalAttributes;
    figure: HtmlGlobalAttributes;
    font: HtmlGlobalAttributes;
    footer: HtmlGlobalAttributes;
    form: HtmlGlobalAttributes & {
      accept?: any;
      "accept-charset"?: any;
      action?: any;
      autocomplete?: any;
      enctype?: any;
      formaction?: any;
      method?: any;
      name?: any;
      novalidate?: any;
      target?: any;
    };
    frame: HtmlGlobalAttributes;
    frameset: HtmlGlobalAttributes;
    h1: HtmlGlobalAttributes;
    h2: HtmlGlobalAttributes;
    h3: HtmlGlobalAttributes;
    h4: HtmlGlobalAttributes;
    h5: HtmlGlobalAttributes;
    h6: HtmlGlobalAttributes;
    head: HtmlGlobalAttributes;
    header: HtmlGlobalAttributes;
    hgroup: HtmlGlobalAttributes;
    hr: HtmlGlobalAttributes & {
      align?: any;
    };
    html: HtmlGlobalAttributes;
    i: HtmlGlobalAttributes;
    iframe: HtmlGlobalAttributes & {
      align?: any;
      allow?: any;
      csp?: any;
      name?: any;
      referrerpolicy?: any;
      sandbox?: any;
      src?: any;
      srcdoc?: any;
      width?: any;
    };
    image: HtmlGlobalAttributes;
    img: HtmlGlobalAttributes & {
      align?: any;
      alt?: any;
      crossorigin?: any;
      decoding?: any;
      ismap?: any;
      referrerpolicy?: any;
      sizes?: any;
      src?: any;
      srcset?: any;
      usemap?: any;
      width?: any;
    };
    input: HtmlGlobalAttributes & {
      accept?: any;
      alt?: any;
      autocomplete?: any;
      capture?: any;
      checked?: any;
      dirname?: any;
      disabled?: any;
      form?: any;
      formaction?: any;
      formenctype?: any;
      formmethod?: any;
      formnovalidate?: any;
      formtarget?: any;
      list?: any;
      max?: any;
      maxlength?: any;
      minlength?: any;
      min?: any;
      multiple?: any;
      name?: any;
      pattern?: any;
      placeholder?: any;
      readonly?: any;
      required?: any;
      size?: any;
      src?: any;
      step?: any;
      type?: any;
      usemap?: any;
      value?: any;
      width?: any;
    };
    ins: HtmlGlobalAttributes & {
      cite?: any;
      datetime?: any;
    };
    kbd: HtmlGlobalAttributes;
    label: HtmlGlobalAttributes & {
      for?: any;
      form?: any;
    };
    legend: HtmlGlobalAttributes;
    li: HtmlGlobalAttributes & {
      value?: any;
    };
    link: HtmlGlobalAttributes & {
      as?: any;
      crossorigin?: any;
      href?: any;
      hreflang?: any;
      integrity?: any;
      media?: any;
      referrerpolicy?: any;
      rel?: any;
      sizes?: any;
      type?: any;
    };
    main: HtmlGlobalAttributes;
    map: HtmlGlobalAttributes & {
      name?: any;
    };
    mark: HtmlGlobalAttributes;
    marquee: HtmlGlobalAttributes & {
      loop?: any;
    };
    math: HtmlGlobalAttributes;
    menu: HtmlGlobalAttributes & {
      type?: any;
    };
    menuitem: HtmlGlobalAttributes;
    meta: HtmlGlobalAttributes & {
      charset?: any;
      content?: any;
      "http-equiv"?: any;
      name?: any;
    };
    meter: HtmlGlobalAttributes & {
      form?: any;
      high?: any;
      low?: any;
      max?: any;
      min?: any;
      optimum?: any;
      value?: any;
    };
    nav: HtmlGlobalAttributes;
    nobr: HtmlGlobalAttributes;
    noembed: HtmlGlobalAttributes;
    noframes: HtmlGlobalAttributes;
    noscript: HtmlGlobalAttributes;
    object: HtmlGlobalAttributes & {
      data?: any;
      form?: any;
      name?: any;
      type?: any;
      usemap?: any;
      width?: any;
    };
    ol: HtmlGlobalAttributes & {
      reversed?: any;
      start?: any;
      type?: any;
    };
    optgroup: HtmlGlobalAttributes & {
      disabled?: any;
      label?: any;
    };
    option: HtmlGlobalAttributes & {
      disabled?: any;
      label?: any;
      selected?: any;
      value?: any;
    };
    output: HtmlGlobalAttributes & {
      for?: any;
      form?: any;
      name?: any;
    };
    p: HtmlGlobalAttributes;
    param: HtmlGlobalAttributes & {
      name?: any;
      value?: any;
    };
    picture: HtmlGlobalAttributes;
    plaintext: HtmlGlobalAttributes;
    portal: HtmlGlobalAttributes;
    pre: HtmlGlobalAttributes;
    progress: HtmlGlobalAttributes & {
      form?: any;
      max?: any;
      value?: any;
    };
    q: HtmlGlobalAttributes & {
      cite?: any;
    };
    rb: HtmlGlobalAttributes;
    rp: HtmlGlobalAttributes;
    rt: HtmlGlobalAttributes;
    rtc: HtmlGlobalAttributes;
    ruby: HtmlGlobalAttributes;
    s: HtmlGlobalAttributes;
    samp: HtmlGlobalAttributes;
    script: HtmlGlobalAttributes & {
      async?: any;
      crossorigin?: any;
      defer?: any;
      integrity?: any;
      language?: any;
      referrerpolicy?: any;
      src?: any;
      type?: any;
    };
    search: HtmlGlobalAttributes;
    section: HtmlGlobalAttributes;
    select: HtmlGlobalAttributes & {
      autocomplete?: any;
      disabled?: any;
      form?: any;
      multiple?: any;
      name?: any;
      required?: any;
      size?: any;
    };
    shadow: HtmlGlobalAttributes;
    slot: HtmlGlobalAttributes;
    small: HtmlGlobalAttributes;
    source: HtmlGlobalAttributes & {
      media?: any;
      sizes?: any;
      src?: any;
      srcset?: any;
      type?: any;
    };
    span: HtmlGlobalAttributes;
    strike: HtmlGlobalAttributes;
    strong: HtmlGlobalAttributes;
    style: HtmlGlobalAttributes & {
      media?: any;
      scoped?: any;
      type?: any;
    };
    sub: HtmlGlobalAttributes;
    summary: HtmlGlobalAttributes;
    sup: HtmlGlobalAttributes;
    table: HtmlGlobalAttributes & {
      align?: any;
      summary?: any;
    };
    tbody: HtmlGlobalAttributes & {
      align?: any;
    };
    td: HtmlGlobalAttributes & {
      align?: any;
      colspan?: any;
      headers?: any;
      rowspan?: any;
    };
    template: HtmlGlobalAttributes;
    textarea: HtmlGlobalAttributes & {
      autocomplete?: any;
      cols?: any;
      dirname?: any;
      disabled?: any;
      enterkeyhint?: any;
      form?: any;
      maxlength?: any;
      minlength?: any;
      name?: any;
      placeholder?: any;
      readonly?: any;
      required?: any;
      rows?: any;
      wrap?: any;
    };
    tfoot: HtmlGlobalAttributes & {
      align?: any;
    };
    th: HtmlGlobalAttributes & {
      align?: any;
      colspan?: any;
      headers?: any;
      rowspan?: any;
      scope?: any;
    };
    thead: HtmlGlobalAttributes & {
      align?: any;
    };
    time: HtmlGlobalAttributes & {
      datetime?: any;
    };
    title: HtmlGlobalAttributes;
    tr: HtmlGlobalAttributes & {
      align?: any;
    };
    track: HtmlGlobalAttributes & {
      default?: any;
      kind?: any;
      label?: any;
      src?: any;
      srclang?: any;
    };
    tt: HtmlGlobalAttributes;
    u: HtmlGlobalAttributes;
    ul: HtmlGlobalAttributes;
    var: HtmlGlobalAttributes;
    video: HtmlGlobalAttributes & {
      autoplay?: any;
      controls?: any;
      crossorigin?: any;
      loop?: any;
      muted?: any;
      playsinline?: any;
      poster?: any;
      preload?: any;
      src?: any;
      width?: any;
    };
    wbr: HtmlGlobalAttributes;
    xmp: HtmlGlobalAttributes;
  }
}
